#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <pwd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <ctype.h>
#include <fcntl.h>
#include <time.h>
#include "pwd_.h"
#include "echo.h"
#include "cd.h"
#include "history.h"
#include <signal.h>
#include <dirent.h>
#include "ls.h"
#include "grp.h"
#include "pinfo.h"
#include "discover.h"
#include "process.h"
